
import { Template, FieldType } from './types';

export const DEFAULT_TEMPLATE: Template = {
  id: 'default-eng',
  name: 'Стандартный чертеж (ГОСТ)',
  fields: [
    { id: '1', key: 'МАТЕРИАЛ ЗАГОТОВКИ', label: 'Материал', type: FieldType.STRING, description: 'Материал с полным названием' },
    { id: '2', key: 'Покрытие', label: 'Покрытие', type: FieldType.STRING, description: 'Покрытие если есть' },
    { id: '3', key: 'Шероховатость', label: 'Шероховатость', type: FieldType.ARRAY_NUMBER, description: 'Числовые значения шероховатостей' },
    { id: '4', key: 'Маркировка', label: 'Маркировка', type: FieldType.BOOLEAN, description: 'Есть ли маркировка?' },
    { id: '5', key: 'Твёрдость', label: 'Твёрдость', type: FieldType.STRING, description: 'Твёрдость если есть' },
    { id: '6', key: 'Закалка', label: 'Закалка', type: FieldType.BOOLEAN, description: 'Закаливать ли деталь?' },
    { id: '7', key: 'Отпуск', label: 'Отпуск', type: FieldType.BOOLEAN, description: 'Нужен ли отпуск детали?' },
    { id: '8', key: 'Номер изделия', label: 'Номер изделия', type: FieldType.STRING, description: 'Номер изделия с чертежа' },
    { id: '9', key: 'Наименование', label: 'Наименование', type: FieldType.STRING, description: 'Наименование детали' },
    { id: '10', key: 'Масса', label: 'Масса', type: FieldType.STRING, description: 'Масса в кг' },
    { id: '11', key: 'Масштаб', label: 'Масштаб', type: FieldType.STRING, description: 'Масштаб чертежа' },
    { id: '12', key: 'ОКРУЖНОСТИ', label: 'Окружности', type: FieldType.ARRAY_NUMBER, description: 'Размеры диаметров окружностей' },
    { id: '13', key: 'ФАСКИ', label: 'Фаски', type: FieldType.ARRAY_STRING, description: 'Размеры фасок' },
    { id: '14', key: 'СКРУГЛЕНИЯ', label: 'Скругления', type: FieldType.ARRAY_NUMBER, description: 'Размеры скруглений' },
  ]
};

export const DEFAULT_SYSTEM_PROMPT = "You are an engineering assistant. Extract specific fields from this drawing. Return ONLY valid JSON.";

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  dashboard: { ru: 'Дашборд', en: 'Dashboard' },
  templates: { ru: 'Шаблоны', en: 'Templates' },
  settings: { ru: 'Настройки', en: 'Settings' },
  activePattern: { ru: 'Активный шаблон', en: 'Active Pattern' },
  processDrawings: { ru: 'Обработка чертежей', en: 'Process Drawings' },
  uploadDescription: { ru: 'Загрузите чертежи (PDF или изображение) для извлечения данных с помощью шаблона', en: 'Upload blueprints (PDF or Image) to extract data using the template' },
  files: { ru: 'файлов', en: 'files' },
  startExtraction: { ru: 'Начать извлечение', en: 'Start Extraction' },
  processingBatch: { ru: 'Обработка...', en: 'Processing...' },
  exportBatch: { ru: 'Экспорт JSON', en: 'Export JSON' },
  exportBatchCsv: { ru: 'Экспорт CSV', en: 'Export CSV' },
  noDrawings: { ru: 'Готов к анализу чертежей.', en: 'Ready to analyze drawings.' },
  uploadFilesPrompt: { ru: 'Загрузите файлы, чтобы начать работу с шаблоном', en: 'Upload files to start working with' },
  pdfDocument: { ru: 'PDF Документ', en: 'PDF Document' },
  viewFullPdf: { ru: 'ОТКРЫТЬ PDF', en: 'VIEW FULL PDF' },
  extractingData: { ru: 'Извлечение данных', en: 'Extracting Data' },
  analyzingShapes: { ru: 'Анализ форм, блоков текста и технических значений...', en: 'Analyzing shapes, text blocks and technical values...' },
  extractionFailed: { ru: 'Ошибка извлечения', en: 'Extraction Failed' },
  copyResult: { ru: 'Копировать', en: 'Copy' },
  process: { ru: 'Запуск', en: 'Process' },
  rerun: { ru: 'Перезапуск', en: 'Re-run' },
  rerunAll: { ru: 'Перезапустить всё', en: 'Re-run All' },
  working: { ru: 'Работаю...', en: 'Working...' },
  notFound: { ru: 'Не найдено', en: 'Not found' },
  yes: { ru: 'ДА', en: 'YES' },
  no: { ru: 'НЕТ', en: 'NO' },
  pending: { ru: 'Ожидание', en: 'Pending' },
  importJson: { ru: 'Импорт JSON', en: 'Import JSON' },
  newTemplate: { ru: 'Новый шаблон', en: 'New Template' },
  extractionTemplates: { ru: 'Шаблоны извлечения', en: 'Extraction Templates' },
  manageTemplates: { ru: 'Создавайте и управляйте правилами извлечения данных.', en: 'Create and manage how data is extracted from your drawings.' },
  use: { ru: 'Использовать', en: 'Use' },
  edit: { ru: 'Правка', en: 'Edit' },
  export: { ru: 'Экспорт', en: 'Export' },
  delete: { ru: 'Удалить', en: 'Delete' },
  saveTemplate: { ru: 'Сохранить', en: 'Save Template' },
  cancel: { ru: 'Отмена', en: 'Cancel' },
  templateName: { ru: 'Название шаблона', en: 'Template Name' },
  fieldsToExtract: { ru: 'Поля для извлечения', en: 'Fields to Extract' },
  addNewField: { ru: 'Добавить поле', en: 'Add New Field' },
  key: { ru: 'Ключ (JSON)', en: 'Key (JSON)' },
  label: { ru: 'Заголовок', en: 'Label' },
  type: { ru: 'Тип', en: 'Type' },
  promptDescription: { ru: 'Промпт / Описание', en: 'Prompt / Description' },
  active: { ru: 'Активен', en: 'Active' },
  noDescription: { ru: 'Описание отсутствует.', en: 'No description provided.' },
  apiSettings: { ru: 'Настройки API', en: 'API Settings' },
  providerSelect: { ru: 'Выберите провайдера AI', en: 'Select AI Provider' },
  geminiDescription: { ru: 'Использовать встроенный Google Gemini API (бесплатно до определенных лимитов).', en: 'Use built-in Google Gemini API (free within certain limits).' },
  openaiDescription: { ru: 'Использовать OpenAI-совместимый API (например, vLLM, Ollama или сам OpenAI).', en: 'Use OpenAI-compatible API (e.g., vLLM, Ollama, or OpenAI itself).' },
  baseUrl: { ru: 'Базовый URL (Base URL)', en: 'Base URL' },
  apiKey: { ru: 'Ключ API (API Key)', en: 'API Key' },
  modelName: { ru: 'Название модели', en: 'Model Name' },
  saveSettings: { ru: 'Сохранить настройки', en: 'Save Settings' },
  settingsSaved: { ru: 'Настройки успешно сохранены', en: 'Settings saved successfully' },
  systemPrompt: { ru: 'Системный промпт', en: 'System Prompt' },
  temperature: { ru: 'Температура (Temperature)', en: 'Temperature' },
  generalSettings: { ru: 'Общие настройки', en: 'General Settings' },
  sha256Hash: { ru: 'SHA256 Хэш', en: 'SHA256 Hash' }
};
