
import { Template, FieldType } from './types';

export const DEFAULT_TEMPLATE: Template = {
  id: 'default-eng',
  name: 'Стандартный чертеж (ГОСТ)',
  fields: [
    { id: '1', key: 'МАТЕРИАЛ ЗАГОТОВКИ', label: 'Материал', type: FieldType.STRING, description: 'Материал с полным названием' },
    { id: '2', key: 'Покрытие', label: 'Покрытие', type: FieldType.STRING, description: 'Покрытие если есть' },
    { id: '3', key: 'Шероховатость', label: 'Шероховатость', type: FieldType.ARRAY_NUMBER, description: 'Числовые значения шероховатостей' },
    { id: '4', key: 'Маркировка', label: 'Маркировка', type: FieldType.BOOLEAN, description: 'Есть ли маркировка?' },
    { id: '5', key: 'Твёрдость', label: 'Твёрдость', type: FieldType.STRING, description: 'Твёрдость если есть' },
    { id: '6', key: 'Закалка', label: 'Закалка', type: FieldType.BOOLEAN, description: 'Закаливать ли деталь?' },
    { id: '7', key: 'Отпуск', label: 'Отпуск', type: FieldType.BOOLEAN, description: 'Нужен ли отпуск детали?' },
    { id: '8', key: 'Номер изделия', label: 'Номер изделия', type: FieldType.STRING, description: 'Номер изделия с чертежа' },
    { id: '9', key: 'Наименование', label: 'Наименование', type: FieldType.STRING, description: 'Наименование детали' },
    { id: '10', key: 'Масса', label: 'Масса', type: FieldType.STRING, description: 'Масса в кг' },
    { id: '11', key: 'Масштаб', label: 'Масштаб', type: FieldType.STRING, description: 'Масштаб чертежа' },
    { id: '12', key: 'ОКРУЖНОСТИ', label: 'Окружности', type: FieldType.ARRAY_NUMBER, description: 'Размеры диаметров окружностей' },
    { id: '13', key: 'ФАСКИ', label: 'Фаски', type: FieldType.ARRAY_STRING, description: 'Размеры фасок' },
    { id: '14', key: 'СКРУГЛЕНИЯ', label: 'Скругления', type: FieldType.ARRAY_NUMBER, description: 'Размеры скруглений' },
  ]
};

export const DEFAULT_SYSTEM_PROMPT = "You are an engineering assistant. Extract specific fields from this drawing. Return ONLY valid JSON.";

export const TRANSLATIONS = {
  ru: {
    dashboard: 'Дашборд',
    templates: 'Шаблоны',
    settings: 'Настройки',
    activePattern: 'Активный шаблон',
    processDrawings: 'Обработка чертежей',
    uploadDescription: 'Загрузите чертежи (PDF или изображение) для извлечения данных с помощью шаблона',
    files: 'файлов',
    startExtraction: 'Начать извлечение',
    processingBatch: 'Обработка...',
    exportBatch: 'Экспорт JSON',
    exportBatchCsv: 'Экспорт CSV',
    noDrawings: 'Готов к анализу чертежей.',
    uploadFilesPrompt: 'Загрузите файлы, чтобы начать работу с шаблоном',
    pdfDocument: 'PDF Документ',
    viewFullPdf: 'ОТКРЫТЬ PDF',
    extractingData: 'Извлечение данных',
    analyzingShapes: 'Анализ форм, блоков текста и технических значений...',
    extractionFailed: 'Ошибка извлечения',
    copyResult: 'Копировать',
    process: 'Запуск',
    rerun: 'Перезапуск',
    rerunAll: 'Перезапустить всё',
    working: 'Работаю...',
    notFound: 'Не найдено',
    yes: 'ДА',
    no: 'НЕТ',
    pending: 'Ожидание',
    importJson: 'Импорт JSON',
    newTemplate: 'Новый шаблон',
    extractionTemplates: 'Шаблоны извлечения',
    manageTemplates: 'Создавайте и управляйте правилами извлечения данных.',
    use: 'Использовать',
    edit: 'Правка',
    export: 'Экспорт',
    delete: 'Удалить',
    saveTemplate: 'Сохранить',
    cancel: 'Отмена',
    templateName: 'Название шаблона',
    fieldsToExtract: 'Поля для извлечения',
    addNewField: 'Добавить поле',
    key: 'Ключ (JSON)',
    label: 'Заголовок',
    type: 'Тип',
    promptDescription: 'Промпт / Описание',
    active: 'Активен',
    noDescription: 'Описание отсутствует.',
    apiSettings: 'Настройки API',
    providerSelect: 'Выберите провайдера AI',
    geminiDescription: 'Использовать встроенный Google Gemini API (бесплатно до определенных лимитов).',
    openaiDescription: 'Использовать OpenAI-совместимый API (например, vLLM, Ollama или сам OpenAI).',
    baseUrl: 'Базовый URL (Base URL)',
    apiKey: 'Ключ API (API Key)',
    modelName: 'Название модели',
    saveSettings: 'Сохранить настройки',
    settingsSaved: 'Настройки успешно сохранены',
    systemPrompt: 'Системный промпт',
    temperature: 'Температура (Temperature)',
    generalSettings: 'Общие настройки',
    sha256Hash: 'SHA256 Хэш'
  },
  en: {
    dashboard: 'Dashboard',
    templates: 'Templates',
    settings: 'Settings',
    activePattern: 'Active Pattern',
    processDrawings: 'Process Drawings',
    uploadDescription: 'Upload blueprints (PDF or Image) to extract data using the template',
    files: 'files',
    startExtraction: 'Start Extraction',
    processingBatch: 'Processing...',
    exportBatch: 'Export JSON',
    exportBatchCsv: 'Export CSV',
    noDrawings: 'Ready to analyze drawings.',
    uploadFilesPrompt: 'Upload files to start working with',
    pdfDocument: 'PDF Document',
    viewFullPdf: 'VIEW FULL PDF',
    extractingData: 'Extracting Data',
    analyzingShapes: 'Analyzing shapes, text blocks and technical values...',
    extractionFailed: 'Extraction Failed',
    copyResult: 'Copy',
    process: 'Process',
    rerun: 'Re-run',
    rerunAll: 'Re-run All',
    working: 'Working...',
    notFound: 'Not found',
    yes: 'YES',
    no: 'NO',
    pending: 'Pending',
    importJson: 'Import JSON',
    newTemplate: 'New Template',
    extractionTemplates: 'Extraction Templates',
    manageTemplates: 'Create and manage how data is extracted from your drawings.',
    use: 'Use',
    edit: 'Edit',
    export: 'Export',
    delete: 'Delete',
    saveTemplate: 'Save Template',
    cancel: 'Cancel',
    templateName: 'Template Name',
    fieldsToExtract: 'Fields to Extract',
    addNewField: 'Add New Field',
    key: 'Key (JSON)',
    label: 'Label',
    type: 'Type',
    promptDescription: 'Prompt / Description',
    active: 'Active',
    noDescription: 'No description provided.',
    apiSettings: 'API Settings',
    providerSelect: 'Select AI Provider',
    geminiDescription: 'Use built-in Google Gemini API (free within certain limits).',
    openaiDescription: 'Use OpenAI-compatible API (e.g., vLLM, Ollama, or OpenAI itself).',
    baseUrl: 'Base URL',
    apiKey: 'API Key',
    modelName: 'Model Name',
    saveSettings: 'Save Settings',
    settingsSaved: 'Settings saved successfully',
    systemPrompt: 'System Prompt',
    temperature: 'Temperature',
    generalSettings: 'General Settings',
    sha256Hash: 'SHA256 Hash'
  }
};
